baseURL = 'https://tonyredondo.github.io/edgarredondo-blog/'
languageCode = 'es-es'
title = 'Edgar Redondo'
theme = 'edgarredondo'
removePathAccents = true

[params]
  description = 'Educador. Divulgador científico. Amante de la Filosofía'
  author = 'Edgar Redondo'

[pagination]
  pagerSize = 10

[taxonomies]
  category = "category"
  tag = "tag"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[permalinks]
  posts = "/:slug/"

[related]
  threshold = 80
  includeNewer = true
  toLower = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[related.indices]]
  name = "tags"
  weight = 100

[[related.indices]]
  name = "categories"
  weight = 80
